global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'concord'
    environment: 'production'

scrape_configs:
  - job_name: 'concord-api'
    static_configs:
      - targets: ['api:9100']
        labels:
          service: 'api'
          tier: 'backend'

  - job_name: 'concord-voice'
    static_configs:
      - targets: ['voice:9101']
        labels:
          service: 'voice'
          tier: 'backend'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          tier: 'database'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          tier: 'cache'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/rules/*.yml'